unit AdT2text;
interface

const
{__AT2REV__}at2rev  = '055';
{__AT2VER__}at2ver  = '2.4.15';
{__AT2DAT__}at2date = '04-17-2014';
{__AT2LNK__}at2link = '12:01pm';

const
  ascii_line_01 = 'ฺ-ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ--๙๚               ๚๙-ฟ';
  ascii_line_02 = 'ณ             ~Û~`ฒ`ฐ         ~Û~`ฒ`ฐ ~ÛÛÛÛÛÛÛÛÛ~`ฒ`ฐ  ~ÛÛÛÛÛÛ~`ฒ`ฐ    ณ';
  ascii_line_03 = 'ณ             ~Û~`ฒ`ฐ         ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ    ~Û~`ฒ`ฐ   ณ';
  ascii_line_04 = '๙        ~Û~`ฒ`ฐ  ~Û~`ฒ`ฐ         ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ    ~Û~`ฒ`ฐ      ~Û~`ฒ`ฐ  ณ';
  ascii_line_05 = '๚       ~Û~`ฒ`ฐ   ~Û~`ฒ`ฐ         ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ  ณ';
  ascii_line_06 = '       ~Û~`ฒ`ฐ    ~Û~`ฒ`ฐ   ~ÛÛÛÛÛÛÛ~`ฒ`ฐ     ~Û~`ฒ`ฐ           ~ÛÛ~`ฒ`ฐ   ณ';
  ascii_line_07 = '      ~Û~`ฒ`ฐ  ~ÛÛÛÛ~`ฒ`ฐ  ~Û~`ฒ`ฐ    ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ          ~Û~`ฒ`ฐ     ณ';
  ascii_line_08 = '     ~Û~`ฒ`ฐ      ~Û~`ฒ`ฐ ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ        ~Û~`ฒ`ฐ       ณ';
  ascii_line_09 = '    ~Û~`ฒ`ฐ       ~Û~`ฒ`ฐ ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ      ~Û~`ฒ`ฐ         ณ';
  ascii_line_10 = '๚  ~Û~`ฒ`ฐ        ~Û~`ฒ`ฐ ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ     ~Û~`ฒ`ฐ  ณ';
  ascii_line_11 = '๙             ~Û~`ฒ`ฐ  ~ÛÛÛÛÛÛÛÛ~`ฒ`ฐ     ~Û~`ฒ`ฐ    ~ÛÛÛÛÛÛÛÛÛÛ~`ฒ`ฐ  ณ';
  ascii_line_12 = 'ภ-ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ--๙๚    ๚๙-ฤฤฤฤฤฤฤฤฤฤฤ-ฤ๙๚  ๚๙-ฤฤฤฤ-ู';
  ascii_line_13 = '         .:: ~THE ULTiMATE FM-TRACKiNG TOOL~ ::.          ';
  ascii_line_14 = 'ฺ-ฤ--๙๚ ๚๙-ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ--๙๚  ๚๙-ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ-ฟ';
  ascii_line_15 = 'ณ `code:`                               ~ฤยฤ       ฤฤ~     ๙';
  ascii_line_16 = 'ณ ~subz3ro/Altair~                 ~/ดDLiBณR/ดCK3R ณณ SDL~ ๚';
  ascii_line_17 = 'ณ `SDL portation support:`          ~ณ       ณ     ฤฤ~      ';
  ascii_line_18 = 'ณ ~Dmitry Smagin~                             ~'+at2ver+'~      ';
  ascii_line_19 = 'ณ `additional ideas:`                                    ๚';
  ascii_line_20 = 'ณ ~Malfunction/Altair~                                   ๙';
  ascii_line_21 = 'ณ `special thanks:`                                      ณ';
  ascii_line_22 = 'ณ ~encore~                HOMEPAGE  www.adlibtracker.net ณ';
  ascii_line_23 = 'ณ ~insane/Altair~         EMAiL     subz3ro@hotmail.com  ณ';
  ascii_line_24 = 'ภ-ฤฤฤฤฤฤฤฤฤฤ--๙๚    ๚๙-ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ-ู';

procedure HELP(topic: String);
procedure C3WriteLn(posX,PosY: Byte; str: String; atr1,atr2,atr3: Byte);
procedure ShowStartMessage;

implementation

uses
    AdT2sys,AdT2vscr,AdT2unit,AdT2keyb,
    StringIO,DialogIO,TxtScrIO;

const
  LINES = 968;
  help_data: array[1..LINES] of String[128] = (
    '@topic:general',
    'อหอออออออออออออออออออออออหอ',
    ' บ `GENERAL KEY REFERENCE` บ',
    'อสอออออออออออออออออออออออสออออออออออออออออออออออออออออออออออออออออออออออออ',
    '~F1~                       Help',
    '~F2 (^S)~                  Save file',
    '~F3 (^L)~                  Load file',
    '~F4 (^A)~                  Toggle Nuke''m dialog',
    '~F5~                       Play',
    '~F6~                       Pause',
    '~F7~                       Stop',
    '~F8~                       Play song from current pattern or order',
    '~F9~                       Play current pattern or order only',
    '~[Ctrl] F8~                @F8 from current line ฟ ',
    '~[Ctrl] F9~                @F9 from current line ร (Pattern Editor)',
    '~[Alt] F6~                 Single-play pattern   ู (~Shift~ toggles trace)',
    '~[Alt] F5~                 @F5 ฟ',
    '@input:alt_f8',
    '~[Alt] F9~                 @F9 ู',
    '@input:shift_f5',
    '~[Shift] F6~               Toggle Debug mode from position at cursor',
    '@input:shift_f8',
    '@input:shift_f9',
    '~[Shift] Space~            Toggle MidiBoard mode ON/OFF',
    '~[Shift] +,-~              Skip to next/previous pattern while Tracing',
    '~+,-~                      Same as above; play pattern from start',
    '',
    'ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    'ณ `WHiLE SONG iS PLAYED WiTH TRACE`           ณ',
    'รฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤด',
    'ณ ~Enter~ ณ Remove Trace and pause playing    ณ',
    'ณ ~Esc~   ณ Remove Trace and continue playing ณ',
    'ภฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู',
    '',
    '~^Enter~                   Play next pattern according to order',
    '~^Left  (Up)~              Rewind current pattern (with Trace)',
    '~^Right (Down)~            Fast-Forward (with Trace)',
    '~^Q~                       Toggle Instrument Macro Editor window',
    '~^E~                       Toggle Arpeggio/Vibrato Macro Editor window',
    '~^M~                       Toggle Macro Browser window',
    '~^F~                       Toggle Song Variables window',
    '~^H~                       Toggle Replace window',
    '~^I~                       Toggle Instrument Control panel',
    '~^O~                       Toggle Octave Control panel',
    '~^P~                       Toggle Pattern List window',
    '~^R~                       Toggle Remap Instrument window',
    '~^T~                       Toggle Transpose window',
    '~^1..^8~                   Quick-set octave',
    '~[Ctrl][Alt] <hold down>~  Toggle Debug Info window (~Shift~ toggles details)',
    '~[Alt] +,-~                Adjust overall volume',
    '~[Alt] C~                  Copy object to clipboard (with selection)',
    '~[Alt] P~                  Paste object from clipboard',
    '~[Alt] M~                  Toggle marking lines ON/OFF',
    '~[Alt] L~                  Toggle Line Marking Setup window',
    '~[Alt] 1..9,0~             Toggle corresponding track ON/OFF',
    '~[Alt] S~                  Set all OFF except current track (solo)',
    '~[Alt] R~                  Reset flags on all tracks',
    '~Asterisk~                 Reverse ON/OFF on all tracks',
    '~F10~                      Toggle Quit Program dialog',
    '~[Shift] F11~              Toggle default (AdT2) behavior mode (optional)',
    '~F11~                      Toggle FastTracker behavior mode (optional)',
    '~F12~                      Toggle Scream Tracker behavior mode (optional)',
    '~[Ctrl][Tab] Up/Down~      Scroll Volume Analyzer section (if necessary)',
    '',
    '@topic:wav_recorder',
    'อหออออออออออออออออออออออออออออหอ',
    ' บ `WAV RECORDER KEY REFERENCE` บ',
    'อสออออออออออออออออออออออออออออสอออออออออออออออออออออออออออออออออออออออออออ',
    '',
    '~[Alt|Ctrl]{Shift} F11~    Toggle WAV recording ON',
    '~[Alt|Ctrl]{Shift} F12~    Toggle WAV recording OFF',
    '',
    'ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    'ณ `FUNCTiONALITY OF ALTERNATiVE KEYS`                    ณ',
    'รฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤด',
    'ณ ~Alt~   ณ Toggle normal recording mode                 ณ',
    'ณ ~Ctrl~  ณ Toggle ''per track'' recording mode            ณ',
    'ณ ~Shift~ ณ Toggle Fade in / Fade out sound processing   ณ',
    'รฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤด',
    'ณ POSSIBLE COMBiNATIONS: Alt,Ctrl,Alt+Shift,Ctrl+Shift ณ',
    'ภฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู',
    '',
    'If ''per track'' recording mode is activated and song playback is stopped,',
    'you can exclude/include corresponding tracks from/to being recorded',
    'with ordinary track selection procedure:',
    '',
    '~[Alt] 1..9,0~             Toggle corresponding track ON/OFF',
    '~[Alt] S~                  Set all OFF except current track (solo)',
    '~[Alt] R~                  Reset flags on all tracks',
    '',
    '@topic:pattern_order',
    'อหอออออออออออออออออออออออออออออหอ',
    ' บ `PATTERN ORDER KEY REFERENCE` บ',
    'อสอออออออออออออออออออออออออออออสออออออออออออออออออออออออออออออออออออออออออ',
    '~Up,Down,Left,Right~       Cursor navigation',
    '~PgUp,PgDn~                Move up/down 32 patterns',
    '~Home,End~                 Move to the top/end of pattern order',
    '~Tab,[Shift] Tab~          Move to next/previous entry',
    '~Insert~                   Insert entry',
    '~Delete~                   Delete entry',
    '~Backspace~                Clear entry',
    '~^Space~                   Enter skip mark',
    '~^C~                       Copy entry to clipboard',
    '~^V~                       Paste entry from clipboard',
    '~+,-~                      Adjust entry',
    '~^F2~                      Save module in tiny format',
    '~Enter~                    Switch to Pattern Editor',
    '',
    'ORDER ENTRiES: 0-7F',
    ' 80-FF = jump to pattern order 0-7F',
    '  syntax: order_number[hex](+80h); e.g. "9A" jumps to order 1A',
    '',
    '@topic:pattern_editor',
    'อหออออออออออออออออออออออออออออออหอ',
    ' บ `PATTERN EDiTOR KEY REFERENCE` บ',
    'อสออออออออออออออออออออออออออออออสอออออออออออออออออออออออออออออออออออออออออ',
    '~Up,Down,Left,Right~       Cursor navigation',
    '~PgUp,PgDn~                Move up/down 16 lines',
    '~Home,End~                 Move to the top/end of current pattern',
    '~Tab,[Shift] Tab~          Move to next/previous track',
    '~[Shift] PgDn,PgUp (+,-)~  Move to next/previous pattern',
    '~[Shift] Home,End~         Move fwd./bckwd. to the first/last pattern',
    '~^Home,^End~               Move to the end/top of previous/next pattern',
    '~Space~                    Advance to next row',
    '~^PgUp,^PgDn~              Transpose note or block halftone up/down',
    '~Backspace~                Remove note or clear attributes',
    '~Insert~                   Insert new line (within track only)',
    '~Delete~                   Delete line (within track only)',
    '~[Shift] Insert~           Insert new line',
    '~[Shift] Delete~           Delete line',
    '~[Shift] Enter~            Toggle fixed and regular note',
    '~^K~                       Insert Key-Off',
    '~^C~                       Copy object at cursor to clipboard',
    '~^V~                       Paste object from clipboard',
    '~[Ctrl][Tab] V~            Multiple paste object from clipboard',
    '~{Ctrl} "[","]"~           Change current instrument',
    '~[Alt] F2~                 Save current pattern to file',
    '~^F2~                      Save module in tiny format',
    '~[Shift] F3~               Quick load recent pattern data',
    '~Enter~                    Switch to Pattern Order',
    '',
    'NOTE SYSTEM: C,C#,D,D#,E,F,F#,G,G#,A,A#,B(H)',
    'VALiD NOTE ENTRiES: C,C-,C#,C1,C-1,C#1...',
    '',
    '@topic:block_operations',
    'ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    'ณ `BLOCK OPERATiONS iN PATTERN EDiTOR`                               ณ',
    'รฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤด',
    'ณ Starting to mark a block: ~[Shift] Up,Down,Left,Right~             ณ',
    'ณ When at least one row in one track is marked, you can continue   ณ',
    'ณ marking also with ~PgUp,PgDn,Home,End~ (~Shift~ is still held down!) ณ',
    'ณ Quick mark: ~[Alt] Q~ (1x-2x-3x) track ฤ pattern ฤ discard       ณ',
    'ณ Toggle last marked block: ~[Alt] B~                                ณ',
    'รฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤด',
    'ณ ~^B~ ณ Blank block  ณ Insert blank block to pattern                ณ',
    'ณ ~^C~ ณ Copy block   ณ Copy block to clipboard                      ณ',
    'ณ ~^D~ ณ Delete block ณ Remove block from pattern                    ณ',
    'ณ ~^N~ ณ Nuke block   ณ Clear block contents                         ณ',
    'ณ ~^V~ ณ Paste block  ณ Paste block from clipbaord to pattern ~(*)~    ณ',
    'ณ ~^X~ ณ Cut block    ณ Combine both Copy and Delete operation       ณ',
    'รฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤด',
    'ณ ~(*)~ PASTE BLOCK OPERATION VARiANTS                               ณ',
    'ณ "Paste block" operation has two other functional variants        ณ',
    'ณ with different key shortcuts for activation:                     ณ',
    'ณ 1) ~[Alt] V~ toggles "Mix block" operation, when block data        ณ',
    'ณ    from clipboard is applied without overwriting existing data;  ณ',
    'ณ 2) ~[Shift] ^V~ toggles "Selective paste block" operation,         ณ',
    'ณ    when only block data from clipboard corresponding to current  ณ',
    'ณ    cursor position is being applied (i.e. note, instrument,      ณ',
    'ณ    1st effect or 2nd effect).                                    ณ',
    'ภฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู',
    '',
    '@topic:pattern_list',
    'อหอออออออออออออออออออออออออออออออออออหอ',
    ' บ `PATTERN LiST WiNDOW KEY REFERENCE` บ',
    'อสอออออออออออออออออออออออออออออออออออสออออออออออออออออออออออออออออออออออออ',
    '~Up,Down~                  Cursor navigation',
    '~PgUp,PgDn~                Move up/down 20 patterns',
    '~Home,End~                 Move to the top/end of pattern list',
    '~Space~                    Mark/Unmark pattern',
    '~^Space~                   Unmark all marked patterns',
    '~[Shift] ^Space~           Reverse marks on all patterns',
    '~[Alt] C (^C)~             Copy pattern to clipboard',
    '~[Alt] P (^V)~             Paste pattern from clipboard',
    '~[Shift] ^V~               Paste pattern data from clipboard',
    '~[Alt] V~                  Paste pattern name(s) from clipboard',
    '~^W~                       Swap marked patterns',
    '~[Shift] ^W~               Swap marked patterns w/o names',
    '~[Shift] Insert~           Insert new pattern',
    '~[Shift] Delete~           Delete pattern',
    '~Enter~                    Rename pattern / Multiple paste',
    '~[Shift] F3~               Quick load recent pattern data',
    '~Esc~                      Return to Pattern Editor or Pattern Order',
    '',
    '@topic:instrument_control',
    'อหออออออออออออออออออออออออออออออออออออออออหอ',
    ' บ `iNSTRUMENT CONTROL PANEL KEY REFERENCE` บ',
    'อสออออออออออออออออออออออออออออออออออออออออสอออออออออออออออออออออออออออออออ',
    '~Up,Down~                  Cursor navigation',
    '~PgUp,PgDn~                Move up/down 16 instruments',
    '~Home,End~                 Move to the top/end of instrument list',
    '~Space~                    Mark/Unmark instrument',
    '~Enter~                    Rename instrument',
    '~^C~                       Copy instrument to clipboard',
    '~[Shift] ^C~               Copy instrument also with macro-definitions',
    '~^V~                       Paste instrument(s) from clipboard',
    '~[Shift] ^V~               Paste instrument data from clipboard',
    '~[Alt] V~                  Paste instrument name(s) from clipboard',
    '~^W~                       Swap marked instruments',
    '~[Shift] ^W~               Swap marked instruments w/o names',
    '~Tab~                      Toggle Instrument Editor window',
    '~[Shift] Tab~              Toggle Macro Editor window',
    '~[Shift] M,B,S,T,C,H~      Toggle ~m~elodic and percussion (~B~D,~S~D,~T~T,T~C~,~H~H)',
    '~[Shift] F2~               Save instrument w/ fm-register macro to file',
    '~[Alt] F2~                 Save instrument bank to file',
    '~^F2~                      Save instrument bank w/ all macros to file',
    '~[Shift] F3~               Quick load recent instrument data',
    '~MBoard keys <hold down>~  Preview instrument',
    '~Esc~                      Return to Pattern Editor or Pattern Order',
    '',
    '@topic:instrument_editor',
    'อหออออออออออออออออออออออออออออออออออออออออหอ',
    ' บ `iNSTRUMENT EDiTOR WiNDOW KEY REFERENCE` บ',
    'อสออออออออออออออออออออออออออออออออออออออออสอออออออออออออออออออออออออออออออ',
    '~Up,Down,Left,Right,~',
    '~Home,End~                 Cursor navigation',
    '~Tab~                      Jump to next setting',
    '~[Shift] Tab~              Jump to previous setting',
    '~PgUp,PgDn (+,-)~          Adjust value',
    '~Space~                    Select item',
    '~^Space~                   Toggle ADSR preview ON/OFF',
    '~[Ctrl] "[","]"~           Change current instrument',
    '~[Ctrl][Shift] "[","]"~    Change macro speed',
    '~Enter~                    Toggle carrier and modulator slot settings',
    '~[Shift] M,B,S,T,C,H~      Toggle ~m~elodic and percussion (~B~D,~S~D,~T~T,T~C~,~H~H)',
    '~[Shift] F2~               Save instrument w/ fm-register macro to file',
    '~MBoard keys <hold down>~  Preview instrument',
    '~Esc~                      Return to Instrument Control panel',
    '',
    '@topic:macro_editor',
    'อหออออออออออออออออออออออออออออออออออออออออออออออหอ',
    ' บ `iNSTRUMENT MACRO EDiTOR WiNDOW KEY REFERENCE` บ',
    'อสออออออออออออออออออออออออออออออออออออออออออออออสอออออออออออออออออออออออออ',
    '~Up,Down,Left,Right~',
    '~Home,End~                 Cursor navigation',
    '~PgUp,PgDown~              Move up/down 16 lines',
    '~Tab (Enter)~              Jump to next field in order',
    '~[Shift] Tab~              Jump to previous field in order',
    '~[Shift] Up,Down~          Synchronous navigation within tables',
    '~[Shift] Home,End~         Move to the start/end of current line in table',
    '~^Left,^Right~             Switch between macro tables',
    '~[Shift] ^Left,^Right~     Navigate to start/end of macro table',
    '~^PgUp,^PgDown~            Change current arpeggio/vibrato table',
    '~[Ctrl] "[","]"~           Change current instrument',
    '~[Ctrl][Shift] "[","]"~    Change macro speed',
    '~^C~                       Copy line in table (whole table respectively)',
    '~[Shift] ^C~               Copy column in table',
    '~^V~                       Paste object from clipboard',
    '~^Enter~                   Paste data from instrument registers',
    '~[Shift] Enter~            Paste data to instrument registers',
    '~[Shift] ^Enter~           Paste data from instrument registers w/ selection',
    '~Backspace~                Clear current item in table',
    '~[Shift] Backspace~        Clear line in table',
    '~[Shift] +,-~              Adjust value at cursor / current item in table',
    '~^Home,^End~               Quick-adjust table length',
    '~[Shift] ^Home,^End~       Quick-adjust loop begin position',
    '~[Shift] ^PgUp,^PgDown~    Quick-adjust loop length',
    '~Insert~                   Insert new line in table',
    '~Delete~                   Delete line in table',
    '~^N~                       Toggle note retrigger ON/OFF       ฟ',
    '~[Alt] ^N~                 Reset flags on all rows            ๖',
    '~^Backspace~               Toggle corresponding column ON/OFF ๖ FM-register',
    '~[Alt] S~                  Set all OFF except current column  ๘ table',
    '~[Alt] R~                  Reset flags on all columns         ๖',
    '~Asterisk~                 Reverse ON/OFF on all columns      ู',
    '~\~                        Toggle current item (switch types only)',
    '~Space~                    Toggle macro-preview mode',
    '~^Space~                   Toggle Key-Off loop within macro-preview mode',
    '~^F2~                      Save instrument bank w/ all macros to file',
    '~Esc~                      Leave Instrument Macro Editor window',
    '',
    '@topic:macro_editor_(av)',
    'อหออออออออออออออออออออออออออออออออออออออออออออออออออออหอ',
    ' บ `APREGGiO/ViBRATO MACRO EDiTOR WiNDOW KEY REFERENCE` บ',
    'อสออออออออออออออออออออออออออออออออออออออออออออออออออออสอออออออออออออออออออ',
    '~Up,Down,Left,Right~',
    '~Home,End~                 Cursor navigation',
    '~PgUp,PgDown~              Move up/down 16 lines',
    '~Tab (Enter)~              Jump to next field in order',
    '~[Shift] Tab~              Jump to previous field in order',
    '~[Shift] Up,Down~          Synchronous navigation within tables',
    '~^Left,^Right~             Switch between macro tables',
    '~[Shift] ^Left,^Right~     Navigate to start/end of macro table',
    '~^PgUp,^PgDown~            Change current arpeggio/vibrato table',
    '~[Ctrl] "[","]"~           Change current instrument',
    '~[Ctrl][Shift] "[","]"~    Change macro speed',
    '~^C~                       Copy line in table (whole table respectively)',
    '~[Shift] ^C~               Copy column in table',
    '~^V~                       Paste object from clipboard',
    '~Backspace~                Clear current item in table',
    '~[Shift] Backspace~        Clear line in table',
    '~[Shift] +,-~              Adjust value at cursor / current item in table',
    '~^Home,^End~               Quick-adjust table length',
    '~[Shift] ^Home,^End~       Quick-adjust loop begin position',
    '~[Shift] ^PgUp,^PgDown~    Quick-adjust loop length',
    '~Space~                    Toggle macro-preview mode',
    '~^Space~                   Toggle Key-Off loop within macro-preview mode',
    '~Esc~                      Leave Arpeggio/Vibrato Macro Editor window',
    '',
    '@topic:macro_browser',
    'อหออออออออออออออออออออออออออออออออออออออออหอ',
    ' บ `iNSTRUMENT MACRO BROWSER KEY REFERENCE` บ',
    'อสออออออออออออออออออออออออออออออออออออออออสอออออออออออออออออออออออออออออออ',
    '~Up,Down,PgUp,PgDown~',
    '~Home,End~                 Cursor navigation',
    '~[Shift] Up,Down~          Move up/down in macro table',
    '~[Shift] Left,Right~       Move left/right in macro table',
    '~[Shift] PgUp,PgDown~      Move page up/down in macro table',
    '~[Shift] Home,End~         Move to the start/end of macro table',
    '~[Ctrl] Home,End~          Move to the start/end of line in macro table',
    '~Enter~                    Load selected macro data',
    '~^Enter~                   Load all macro data from bank (if available)',
    '~[Ctrl] "[","]"~           Change current instrument (if possible)',
    '~[Ctrl][Shift] "[","]"~    Change macro speed',
    '~MBoard keys <hold down>~  Preview instrument with selected macro data',
    '~Tab~                      Switch to Arpeggio/Vibrato Macro Browser window',
    '~Esc~                      Leave Instrument Macro Browser window',
    '',
    '@topic:macro_browser_av',
    'อหออออออออออออออออออออออออออออออออออออออออออออออหอ',
    ' บ `ARPEGGiO/ViBRATO MACRO BROWSER KEY REFERENCE` บ',
    'อสออออออออออออออออออออออออออออออออออออออออออออออสอออออออออออออออออออออออออ',
    '~Up,Down,PgUp,PgDown~',
    '~Home,End~                 Cursor navigation',
    '~[Shift] Left,Right~       Move left/right in arpeggio table      ฟ',
    '~[Shift] PgUp,PgDown~      Move page left/right in arpeggio table ๖',
    '~^Left,^Right~             Move left/right in vibrato table       ๘ refer to',
    '~^PgUp,^PgDown~            Move page left/right in vibrato table  ๖ ~(*)~',
    '~[Shift] Space~            Toggle arpeggio table selection        ๖',
    '~^Space~                   Toggle vibrato table selection         ู',
    '~[Shift] Home,End~         Navigate to start/end of arpeggio table',
    '~^Home,^End~               Navigate to start/end of vibrato table',
    '~[Ctrl] "[","]"~           Change current instrument (if possible)',
    '~[Ctrl][Shift] "[","]"~    Change macro speed',
    '~MBoard keys <hold down>~  Preview instrument with selected macro data',
    '~Enter~                    Load selected macro data',
    '~^Enter~                   Load all macro data from bank (if available)',
    '~Esc~                      Leave Arpeggio/Vibrato Macro Browser window',
    '',
    '~(*)~ Key combination with ~Ctrl+Shift~ applies action to both tables',
    '',
    '@topic:remap_dialog',
    'อหอออออออออออออออออออออออออออออออออออออออหอ',
    ' บ `REMAP iNSTRUMENT WiNDOW KEY REFERENCE` บ',
    'อสอออออออออออออออออออออออออออออออออออออออสออออออออออออออออออออออออออออออออ',
    '~Up,Down,Left,Right,~',
    '~Home,End~                 Cursor navigation',
    '~PgUp,PgDown~              Move up/down 16 instruments',
    '~Tab~                      Jump to next selection',
    '~[Shift] Tab~              Jump to previous selection',
    '~MBoard keys <hold down>~  Preview instrument',
    '~Enter~                    Remap',
    '~Esc~                      Return to Pattern Editor or Pattern Order',
    '',
    '@topic:replace_dialog',
    'อหออออออออออออออออออออออออออออออหอ',
    ' บ `REPLACE WiNDOW KEY REFERENCE` บ',
    'อสออออออออออออออออออออออออออออออสอออออออออออออออออออออออออออออออออออออออออ',
    '~Up,Down,Left,Right,~',
    '~Home,End~                 Cursor navigation',
    '~Tab~                      Jump to next selection',
    '~[Shift] Tab~              Jump to previous selection',
    '~^K~                       Insert Key-Off in note column',
    '~^N~                       Mark "new" field to clear found item',
    '~Delete,Backspace~         Delete current/previous character',
    '~^Backspace~               Delete whole "to find" or "replace" mask',
    '~Space~                    Toggle prompt on replace',
    '~Enter~                    Replace',
    '~Esc~                      Return to Pattern Editor or Pattern Order',
    '',
    '@topic:song_variables',
    'อหอออออออออออออออออออออออออออออออออออออหอ',
    ' บ `SONG VARiABLES WiNDOW KEY REFERENCE` บ',
    'อสอออออออออออออออออออออออออออออออออออออสออออออออออออออออออออออออออออออออออ',
    '~Up,Down,Left,Right~       Cursor navigation',
    '~Tab (Enter)~              Jump to next variable field',
    '~[Shift] Tab~              Jump to previous variable field',
    '~Space~                    Select item',
    '~Esc~                      Return to Pattern Editor or Pattern Order',
    '',
    '@topic:input_field',
    'อหอออออออออออออออออออออออออออหอ',
    ' บ `iNPUT FiELD KEY REFERENCE` บ',
    'อสอออออออออออออออออออออออออออสออออออออออออออออออออออออออออออออออออออออออออ',
    '',
    '~Left,Right~               Move left/right',
    '~Home,End~                 Move to the begin/end',
    '~^Left,^Right~             Move word left/right',
    '~Backspace,Delete~         Delete character left/right',
    '~^Backspace,^T~            Delete word left/right',
    '~^Y~                       Delete string',
    '~Insert~                   Toggle input and overwrite mode',
    '',
    '@topic:midiboard',
    'อหอออออออออออออออออออออออออหอ',
    ' บ `MiDiBOARD KEY REFERENCE` บ',
    'อสอออออออออออออออออออออออออสออออออออออออออออออออออออออออออออออออออออออออออ',
    '',
    '     C#  D#      F#  G#  A#      C#  D#      F#  G#  A#      C#  D#',
    '',
    '  ÞÛÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛÛ',
    '  ÞÛÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛÛ',
    '  ÞÛÛ ~S~ÞÛ ~D~ÞÛÛÞÛÛ ~G~ÞÛ ~H~ÞÛ ~J~ÞÛÛÞÛÛ ~2~ÞÛ ~3~ÞÛÛÞÛÛ ~5~ÞÛ ~6~ÞÛ ~7~ÞÛÛÞÛÛ ~9~ÞÛ ~0~ÞÛÛ',
    '  ÞÛÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛÛ',
    '  ÞÛÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛ  ÞÛÛÞÛÛ  ÞÛ  ÞÛÛ',
    '  ÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛ',
    '  ÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛ',
    '  ÞÝ~Z~ÞÞÝ~X~ÞÞÝ~C~ÞÞÝ~V~ÞÞÝ~B~ÞÞÝ~N~ÞÞÝ~M~ÞÞÝ~Q~ÞÞÝ~W~ÞÞÝ~E~ÞÞÝ~R~ÞÞÝ~T~ÞÞÝ~Y~ÞÞÝ~U~ÞÞÝ~I~ÞÞÝ~O~ÞÞÝ~P~Þ',
    '  ÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛ',
    '  ÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛÞÛÛÛ',
    '',
    '    C   D   E   F   G   A   B   C   D   E   F   G   A   B   C   D   E',
    '',
    'ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    'ณ `WHiLE TRACKER iS iN MiDiBOARD MODE`                                    ณ',
    'รฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤด',
    'ณ ~MBoard key~ copies note in note field, plays it, and advances song     ณ',
    'ณ to next row. If used with ~Left-Shift~ key and line marking toggled ON, ณ',
    'ณ it advances song to next highlighted row.                             ณ',
    'ณ If used with ~Right-Shift~ key, it makes a fixed note.                  ณ',
    'ณ ~Space~ plays row and advances song by one row.                         ณ',
    '@@`ณ ~`~ inserts Key-Off, releases playing note and advances to next row.    ณ',
    'ภฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู',
    '',
    '@topic:instrument_registers',
    'อหออออออออออออออออออออออหอ',
    ' บ `iNSTRUMENT REGiSTERS` บ',
    'อสออออออออออออออออออออออสอออออออออออออออออออออออออออออออออออออออออออออออออ',
    '~Attack rate~',
    'Indicates how fast the sound volume goes to maximum.',
    '1=slow, 15=fast. 0 means no attack phase.',
    '',
    '~Decay rate~',
    'Indicates how fast the sound goes from maximum level to sustain level.',
    '1=slow, 15=fast. 0 means no decay phase.',
    '',
    '~Sustain level~',
    'Indicates the sustain level.',
    '1=loudest, 15=softest. 0 means no sustain phase.',
    '',
    '~Release rate~',
    'Indicates how fast the sound goes from sustain level to zero level.',
    '1=slow, 15=fast. 0 means no release phase.',
    '',
    '~Output level~',
    'Ranges from 0 to 63, indicates the attenuation according to the',
    'envelope generator output. In Additive synthesis, varying',
    'the output level of any operator varies the volume of its corresponding',
    'channel. In FM synthesis, varying the output level of carrier varies',
    'the volume of its corresponding channel, but varying the output of',
    'the modulator will change the frequency spectrum produced by the carrier.',
    '',
    '~Waveform select~',
    'Specifies the output waveform type.',
    'The first is closest to pure sine wave, the last is most distorted.',
    '',
    '`[0] SiNE`',
    '',
    '     ',
    '     ณ',
    '     ณ     __                      __',
    '     ณ   /    \                  /    \',
    '     ณ /        \              /        \',
    '    ฤลฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤยฤฤฤ',
    '     ณ             \        /              \        /',
    '     ณ               \    /                  \    /',
    '     ณ                                       ',
    '     ณ          /2                    3/2         2',
    '',
    '',
    '`[1] HALF-SiNE`',
    '',
    '     ',
    '     ณ',
    '     ณ     __                      __',
    '     ณ   /    \                  /    \',
    '     ณ /        \              /        \',
    '    ฤลฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤยฤฤฤ',
    '     ณ',
    '     ณ          /2                    3/2         2',
    '     ณ',
    '     ณ',
    '',
    '',
    '`[2] ABS-SiNE`',
    '',
    '     ',
    '     ณ',
    '     ณ     __         __           __         __',
    '     ณ   /    \     /    \       /    \     /    \',
    '     ณ /        \ /        \   /        \ /        \',
    '    ฤลฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤยฤฤฤ',
    '     ณ',
    '     ณ          /2                     3/2        2',
    '     ณ',
    '     ณ',
    '',
    '',
    '`[3] PULSE-SiNE`',
    '',
    '     ',
    '     ณ',
    '     ณ    _           _           _           _',
    '     ณ  /  |        /  |        /  |        /  |',
    '     ณ/    |      /    |      /    |      /    |',
    '    ฤลฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤ',
    '     ณ',
    '     ณ    /4   /2   3/4       5/4  3/2  7/4   2',
    '     ณ',
    '     ณ',
    '',
    '',
    '`[4] SiNE, EVEN PERiODS ONLY (EPO)`',
    '',
    '     ',
    '     ณ',
    '     ณ',
    '     ณ /\                     /\',
    '     ณ/   \                   /   \',
    '    ฤลฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤ',
    '     ณ      \   /                   \   /',
    '     ณ       \_/                     \_/',
    '     ณ',
    '     ณ    /4   /2   3/4       5/4  3/2  7/4   2',
    '',
    '',
    '`[5] ABS-SiNE, EVEN PERiODS ONLY (EPO)`',
    '',
    '     ',
    '     ณ',
    '     ณ',
    '     ณ /\   /\               /\   /\',
    '     ณ/   \ /   \             /   \ /   \',
    '    ฤลฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤ',
    '     ณ',
    '     ณ    /4   /2   3/4       5/4  3/2  7/4   2',
    '     ณ',
    '     ณ',
    '',
    '',
    '`[6] SQUARE`',
    '',
    '     ',
    '     ณ',
    '     ณ',
    '     ร-----------ฟ           ฺ-----------ฟ',
    '     |           |           |           |',
    '    ฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤยฤฤฤ',
    '     ณ           |           |           |           |',
    '     ณ           ภ-----------ู           ภ-----------ู',
    '     ณ',
    '     ณ          /2                    3/2         2',
    '',
    '',
    '`[7] DERiVED SQUARE`',
    '',
    '     ',
    '     ณ',
    '     |\                      |\',
    '     | __                  | __',
    '     |     ฤฤ__            |     ฤฤ__',
    '    ฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤฤฤยฤฤฤ',
    '     ณ            ฤฤ__     |            ฤฤ__     |',
    '     ณ                  __ |                  __ |',
    '     ณ                      \|                      \|',
    '     ณ          /2                    3/2         2',
    '',
    '',
    '~Key scaling level (KSL)~',
    'When set, makes the sound softer at higher frequencies.',
    'With musical instruments, volume decreases as pitch increases.',
    'Level key scaling values are used to simulate this effect.',
    'If any (not zero), the diminishing factor can be 1.5 dB/octave,',
    '3.0 dB/octave, or 6.0 dB/octave.',
    '',
    '~Panning~',
    'Gives you ability of controlling output, going to left or right channel,',
    'standing in the middle respectively.',
    'The parameter corresponds either with carrier and modulator, therefore',
    'it is listed only once (within the carrier slot).',
    '',
    '~Fine-tune~',
    'This is not a hardware parameter.',
    'Ranges from -127 to 127, it indicates the number of frequency units',
    'shifted up or down for any note playing with the corresponding instrument.',
    'The parameter corresponds either with carrier and modulator, therefore',
    'it is listed only once (within the carrier slot).',
    '',
    '~Feedback strength~',
    'Ranges from 0 to 7, it indicates the modulation depth',
    'for the modulator slot FM feedback.',
    '',
    'ฺฤฤฤฤฤฤฤฤฤฤฤฤาฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤฟ',
    'ณ `Feedback`   บ `[0]` ณ `[1]` ณ `[2]` ณ `[3]` ณ `[4]` ณ `[5]` ณ `[6]` ณ `[7]` ณ',
    'รฤฤฤฤฤฤฤฤฤฤฤฤืฤฤฤฤฤลฤฤฤฤฤลฤฤฤฤฤลฤฤฤฤฤลฤฤฤฤฤลฤฤฤฤฤลฤฤฤฤฤลฤฤฤฤฤด',
    'ณ `Modulation` บ  0  ณ/16 ณ /8 ณ /4 ณ /2 ณ    ณ 2  ณ 4  ณ',
    'ภฤฤฤฤฤฤฤฤฤฤฤฤะฤฤฤฤฤมฤฤฤฤฤมฤฤฤฤฤมฤฤฤฤฤมฤฤฤฤฤมฤฤฤฤฤมฤฤฤฤฤมฤฤฤฤฤู',
    '',
    'The parameter corresponds either with carrier and modulator, therefore',
    'it is listed only once (within the carrier slot).',
    '',
    '~Connection type~',
    'Frequency modulation means that the modulator slot modulates the carrier.',
    'Additive synthesis means that both slots produce sound on their own.',
    '',
    '`[FM] FREQUENCY MODULATION`',
    '',
    '',
    '        ฺฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    '        ณ            ณ',
    '            ษออออป  ณ         ษออออป',
    ' P1 ฤฤ(+)ฤฤบ MO วฤฤมฤฤ(+)ฤฤบ CA วฤฤ OUT',
    '             ศออออผ           ศออออผ',
    '                          ณ',
    '',
    '                          P2',
    '',
    '`[ADDiTiVE SYNTHESiS] AM`',
    '',
    '',
    '        ฺฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    '        ณ            ณ',
    '            ษออออป  ณ',
    ' P1 ฤฤ(+)ฤฤบ MO วฤฤมฤฤฤฤฟ',
    '             ศออออผ       ณ',
    '                          ',
    '                         (+)ฤฤ OUT',
    '                          ',
    '             ษออออป       ณ',
    ' P2 ฤฤฤฤฤฤฤฤบ CA วฤฤฤฤฤฤฤู',
    '             ศออออผ',
    '',
    'The parameter corresponds either with carrier and modulator, therefore',
    'it is listed only once (within the carrier slot).',
    'This parameter is also very important when making 4-op instruments,',
    'because the combination of two instrument connections specifies',
    'the connection of the 4-op instrument as shown below:',
    '',
    '`[FM/FM]`',
    '',
    '        ฺฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    '        ณ            ณ',
    '            ษออออป  ณ         ษออออป         ษออออป         ษออออป',
    ' P1 ฤฤ(+)ฤฤบ M1 วฤฤมฤฤ(+)ฤฤบ C1 วฤฤ(+)ฤฤบ M2 วฤฤ(+)ฤฤบ C2 วฤฤ OUT',
    '             ศออออผ           ศออออผ        ศออออผ        ศออออผ',
    '                          ณ              ณ              ณ',
    '',
    '                          P2             P3             P4',
    '',
    '`[FM/AM]`',
    '',
    '        ฺฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    '        ณ            ณ',
    '            ษออออป  ณ         ษออออป',
    ' P1 ฤฤ(+)ฤฤบ M1 วฤฤมฤฤ(+)ฤฤบ C1 วฤฤฤฤฟ',
    '             ศออออผ           ศออออผ    ณ',
    '                          ณ              ณ',
    '                                         ',
    '                          P2            (+)ฤฤ OUT',
    '                                         ',
    '                                         ณ',
    '             ษออออป            ษออออป    ณ',
    ' P3 ฤฤฤฤฤฤฤฤบ M2 วฤฤฤฤฤ(+)ฤฤบ C2 วฤฤฤฤู',
    '             ศออออผ           ศออออผ',
    '                          ณ',
    '',
    '                          P4',
    '',
    '`[AM/FM]`',
    '',
    '        ฺฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    '        ณ            ณ',
    '            ษออออป  ณ',
    ' P1 ฤฤ(+)ฤฤบ M1 วฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    '             ศออออผ                                     ณ',
    '                                                        ณ',
    '                                                        ณ',
    '                                                        ณ',
    '             ษออออป            ษออออป         ษออออป    ',
    ' P2 ฤฤฤฤฤฤฤฤบ C1 วฤฤฤฤฤ(+)ฤฤบ M2 วฤฤ(+)ฤฤบ C2 วฤฤ(+)ฤฤ OUT',
    '             ศออออผ           ศออออผ        ศออออผ',
    '                          ณ              ณ',
    '',
    '                          P3             P4',
    '',
    '`[AM/AM]`',
    '',
    '        ฺฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    '        ณ            ณ',
    '            ษออออป  ณ',
    ' P1 ฤฤ(+)ฤฤบ M1 วฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    '             ศออออผ                      ณ',
    '                                         ณ',
    '                                         ณ',
    '                                         ณ',
    '             ษออออป            ษออออป    ',
    ' P2 ฤฤฤฤฤฤฤฤฤบ C1 วฤฤฤฤฤ(+)ฤฤบ M2 วฤฤ(+)ฤฤ OUT',
    '             ศออออผ           ศออออผ    ',
    '                          ณ              ณ',
    '                                         ณ',
    '                          P3             ณ',
    '             ษออออป                      ณ',
    ' P4 ฤฤฤฤฤฤฤฤบ C2 วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู',
    '             ศออออผ',
    '',
    '~Tremolo (Amplitude modulation)~',
    'When set, turns tremolo (volume vibrato) ON for the corresponding slot.',
    'The repetition rate is 3.7, the depth is optional (1dB/4.8dB).',
    '',
    '~Vibrato~',
    'When set, turns frequency vibrato ON for the corresponding slot.',
    'The repetition rate is 6.1, the depth is optional (7%/14%).',
    '',
    '~Key scale rate (KSR)~',
    'When set, makes the sound shorter at higher frequencies.',
    'With normal musical instruments, the attack and decay rate becomes faster',
    'as the pitch increases. The key scale rate controls simulation of',
    'this effect. An offset (rof) is added to the individual attack, decay,',
    'and release rates depending on the following formula:',
    '',
    'actual_rate = (rate  4) + rof',
    '',
    'The "rof" values for corresponding "rate" value and KSR state are shown',
    'in the following table:',
    '',
    'ฺฤฤฤฤฤฤฤฤาฤฤฤยฤฤฤยฤฤฤยฤฤฤยฤฤฤยฤฤฤยฤฤฤยฤฤฤยฤฤฤยฤฤฤยฤฤฤยฤฤฤยฤฤฤยฤฤฤยฤฤฤยฤฤฤฟ',
    'ณ `%rate%` บ 0 ณ 1 ณ 2 ณ 3 ณ 4 ณ 5 ณ 6 ณ 7 ณ 8 ณ 9 ณ A ณ B ณ C ณ D ณ E ณ F ณ',
    'ฦออออออออฮอออุอออุอออุอออุอออุอออุอออุอออุอออุอออุอออุอออุอออุอออุอออุอออต',
    'ณ `[OFF]`  บ 0 ณ 0 ณ 0 ณ 0 ณ 1 ณ 1 ณ 1 ณ 1 ณ 2 ณ 2 ณ 2 ณ 2 ณ 3 ณ 3 ณ 3 ณ 3 ณ',
    'รฤฤฤฤฤฤฤฤืฤฤฤลฤฤฤลฤฤฤลฤฤฤลฤฤฤลฤฤฤลฤฤฤลฤฤฤลฤฤฤลฤฤฤลฤฤฤลฤฤฤลฤฤฤลฤฤฤลฤฤฤลฤฤฤด',
    'ณ `[ON]`   บ 0 ณ 1 ณ 2 ณ 3 ณ 4 ณ 5 ณ 6 ณ 7 ณ 8 ณ 9 ณ A ณ B ณ C ณ D ณ E ณ F ณ',
    'ภฤฤฤฤฤฤฤฤะฤฤฤมฤฤฤมฤฤฤมฤฤฤมฤฤฤมฤฤฤมฤฤฤมฤฤฤมฤฤฤมฤฤฤมฤฤฤมฤฤฤมฤฤฤมฤฤฤมฤฤฤมฤฤฤู',
    '',
    '~Sustain (Envelope generator type)~',
    'When set, the sustain level of the voice is maintained until released.',
    'When clear, the sound begins to decay immediately after hitting',
    'the sustain phase.',
    '',
    '`[OFF]`                /\  DR',
    '                   /    \',
    '                 /     ...\...SL',
    '           AR  /            \',
    '             /                \  RR',
    '           /                    \',
    '      _ _/                        \_ _ _',
    '         .',
    '         :',
    '         ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ',
    '      ฤฤฤู     KEY ON',
    '',
    '',
    '`[ON]`                 /\  DR',
    '                   /    \      SL',
    '                 /        \ _ _ _ _ _',
    '           AR  /                      \',
    '             /                       :  \  RR',
    '           /                         :    \',
    '      _ _/                           :      \_ _ _',
    '         .                           :',
    '         :                           :',
    '         ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ  KEY OFF',
    '      ฤฤฤู     KEY ON                ภฤฤฤฤฤฤฤฤฤฤฤฤ',
    '',
    '',
    '~Frequency data multiplier~',
    'Sets the multiplier for the frequency data specified by block and',
    'F-number. This multiplier is applied to the FM carrier or modulation',
    'frequencies. The multiplication factor and corresonding harmonic types are',
    'shown in the following table:',
    '',
    'ฺฤฤฤฤฤฤฤยฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ',
    'ณ `Mult.` ณ  ``  ณ `Harmonic`                           ณ',
    'ฦอออออออุอออออุออออออออออออออออออออออออออออออออออออต',
    'ณ  `[0]`  ณ 0.5 ณ 1 octave below                     ณ',
    'ณ  `[1]`  ณ  1  ณ at the voice''s specified frequency ณ',
    'ณ  `[2]`  ณ  2  ณ 1 octave above                     ณ',
    'ณ  `[3]`  ณ  3  ณ 1 octave and a 5th above           ณ',
    'ณ  `[4]`  ณ  4  ณ 2 octaves above                    ณ',
    'ณ  `[5]`  ณ  5  ณ 2 octaves and a Major 3rd above    ณ',
    'ณ  `[6]`  ณ  6  ณ 2 octaves and a 5th above          ณ',
    'ณ  `[7]`  ณ  7  ณ 2 octaves and a Minor 7th above    ณ',
    'ณ  `[8]`  ณ  8  ณ 3 octaves above                    ณ',
    'ณ  `[9]`  ณ  9  ณ 3 octaves and a Major 2nd above    ณ',
    'ณ  `[A]`  ณ 10  ณ 3 octaves and a Major 3rd above    ณ',
    'ณ  `[B]`  ณ 11  ณ " "       "   " "     "   "        ณ',
    'ณ  `[C]`  ณ 12  ณ 3 octaves and a 5th above          ณ',
    'ณ  `[D]`  ณ 13  ณ " "       "   "     "              ณ',
    'ณ  `[E]`  ณ 14  ณ 3 octaves and a Major 7th above    ณ',
    'ณ  `[F]`  ณ 15  ณ " "       "   " "     "   "        ณ',
    'ภฤฤฤฤฤฤฤมฤฤฤฤฤมฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู',
    '',
    '@topic:effects',
    'อหอออออออออออออออออออหอ',
    ' บ `SUPPORTED EFFECTS` บ',
    'อสอออออออออออออออออออสออออออออออออออออออออออออออออออออออออออออออออออออออออ',
    '`0`xy ฤฤ ARPEGGiO                   xy=1st_ซtone|2nd_ซtone  [1-F]',
    '`1`xx ฤฤ FREQUENCY SLiDE UP         xx=speed_of_slide       [1-FF]',
    '`2`xx ฤฤ FREQUENCY SLiDE DOWN       xx=speed_of_slide       [1-FF]',
    '`3`xx ฤฤ TONE PORTAMENTO            xx=speed_of_slide       [1-FF] ~C~',
    '`4`xy ฤฤ ViBRATO                    xy=speed|depth          [1-F]  ~C~',
    '`5`xy ฤฤ ~3xx~ & VOLUME SLiDE         xy=up_speed|down_speed  [1-F]  ~C~',
    '`6`xy ฤฤ ~4xy~ & VOLUME SLiDE         xy=up_speed|down_speed  [1-F]  ~C~',
    '`7`xx ฤฤ FiNE FREQUENCY SLiDE UP    xx=speed_of_slide       [1-FF]',
    '`8`xx ฤฤ FiNE FREQUENCY SLiDE DOWN  xx=speed_of_slide       [1-FF]',
    '`9`xx ฤฤ SET MODULATOR VOLUME       xx=volume_level         [0-3F]',
    '`A`xy ฤฤ VOLUME SLiDE               xy=up_speed|down_speed  [1-F]',
    '`B`xx ฤฤ POSiTiON JUMP              xx=position_in_order    [0-7F]',
    '`C`xx ฤฤ SET iNSTRUMENT VOLUME      xx=volume_level         [0-3F]',
    '`D`xx ฤฤ PATTERN BREAK              xx=line_in_next_pattern [0-FF]',
    '`E`xx ฤฤ SET TEMPO                  xx=bpm_in_             [1-FF]',
    '`F`xx ฤฤ SET SPEED                  xx=frames_per_row       [1-FF]',
    '`G`xy ฤฤ ~3xx~ & FiNE VOLUME SLiDE    xy=up_speed|down_speed  [1-F]  ~C~',
    '`H`xy ฤฤ ~4xy~ & FiNE VOLUME SLiDE    xy=up_speed|down_speed  [1-F]  ~C~',
    '`I`xx ฤฤ SET CARRiER VOLUME         xx=volume_level         [0-3F]',
    '`J`xy ฤฤ SET WAVEFORM               xy=carrier|modulator    [0-7,F=NiL]',
    '`K`xy ฤฤ FiNE VOLUME SLiDE          xy=up_speed|down_speed  [1-F]',
    '`L`xx ฤฤ RETRiG NOTE                xx=interval             [1-FF]',
    '`M`xy ฤฤ TREMOLO                    xy=speed|depth          [1-F]  ~C~',
    '`N`xy ฤฤ TREMOR                     xy=on_time|off_time     [1-F]',
    '`O`xy ฤฤ ~0xy~ & VOLUME SLiDE         xy=up_speed|down_speed  [1-F]  ~C~',
    '`P`xy ฤฤ ~0xy~ & FiNE VOLUME SLiDE    xy=up_speed|down_speed  [1-F]  ~C~',
    '`Q`xy ฤฤ MULTi RETRiG NOTE          xy=interval|vol_change  [1-F]',
    '',
    '`Q`x?  `0` = None         `8` = Unused',
    '     `1` = -1           `9` = +1',
    '     `2` = -2           `A` = +2',
    '     `3` = -4           `B` = +4',
    '     `4` = -8           `C` = +8',
    '     `5` = -16          `D` = +16',
    '     `6` = 2/3         `E` = 3/2',
    '     `7` = 1/2         `F` = 2',
    '',
    '`R`xy ฤฤ ~1xx~ ฟ                   ฟ',
    '`S`xy ฤฤ ~2xx~ ๖ &                 ๖',
    '`T`xy ฤฤ ~7xx~ ๘ VOLUME SLiDE      ๖',
    '`U`xy ฤฤ ~8xx~ ู                   ๖',
    '`V`xy ฤฤ ~1xx~ ฟ                   ๘  xy=up_speed|down_speed  [1-F]  ~C~',
    '`W`xy ฤฤ ~2xx~ ๖ &                 ๖',
    '`X`xy ฤฤ ~7xx~ ๘ FiNE VOLUME SLiDE ๖',
    '`Y`xy ฤฤ ~8xx~ ู                   ู',
    '',
    '`Z`?? `0`x SET TREMOLO DEPTH          x=1dB/4.8dB             [0-1]',
    '    `1`x SET ViBRATO DEPTH          x=7%/14%                [0-1]',
    '    `2`x SET ATTACK RATE   ฟ        x=attack_rate           [0-F]',
    '    `3`x SET DECAY RATE    ๖ MOD.   x=decay_rate            [0-F]',
    '    `4`x SET SUSTAiN LEVEL ๘        x=sustain_level         [0-F]',
    '    `5`x SET RELEASE RATE  ู        x=release_rate          [0-F]',
    '    `6`x SET ATTACK RATE   ฟ        x=attack_rate           [0-F]',
    '    `7`x SET DECAY RATE    ๖ CAR.   x=decay_rate            [0-F]',
    '    `8`x SET SUSTAiN LEVEL ๘        x=sustain_level         [0-F]',
    '    `9`x SET RELEASE RATE  ู        x=release_rate          [0-F]',
    '    `A`x SET FEEDBACK STRENGTH      x=feedback_strength     [0-7]',
    '    `B`x SET PANNiNG POSiTiON       x=panning_position      [0-2]',
    '    `C`x PATTERN LOOP               x=parameter             [0-F]',
    '    `D`x RECURSiVE PATTERN LOOP     x=parameter             [0-F]',
    '    `E`x MACRO KEY-OFF LOOP         x=off/on                [0-1]',
    '',
    '`ZB`?  `0` = Center',
    '     `1` = Left',
    '     `2` = Right',
    '`ZC`?',
    '`ZD`?  `0` = Set loopback point',
    '     x = Loop ~x~ times',
    '',
    '`ZF`?  `0` RELEASE SUSTAiNiNG SOUND',
    '     `1` RESET iNSTRUMENT VOLUME',
    '     `2` LOCK TRACK VOLUME',
    '     `3` UNLOCK TRACK VOLUME ',
    '     `4` LOCK VOLUME PEAK',
    '     `5` UNLOCK VOLUME PEAK',
    '     `6` TOGGLE MODULATOR VOLUME SLiDES',
    '     `7` TOGGLE CARRiER VOLUME SLiDES',
    '     `8` TOGGLE DEFAULT VOLUME SLiDES',
    '     `9` LOCK TRACK PANNiNG',
    '     `A` UNLOCK TRACK PANNiNG',
    '     `B` ViBRATO OFF',
    '     `C` TREMOLO OFF',
    '     `D` FORCE FiNE ViBRATO',
    '     `E` FORCE FiNE TREMOLO',
    '     `F` FORCE NO RESTART FOR MACRO TABLES',
    '',
    '`!`xx ฤฤ SWAP ARPEGGiO TABLE        xx=table_number         [0-FF]',
    '`@`xx ฤฤ SWAP ViBRATO TABLE         xx=table_number         [0-FF]',
    '`=`xx ฤฤ FORCE iNSTRUMENT VOLUME    xx=volume_level         [0-3F]',
    '`%`xx ฤฤ SET GLOBAL VOLUME          xx=volume_level         [0-3F]',
    '',
    '`#`?? `0`x SET CONNECTiON TYPE        x=FM/AM                 [0-1]',
    '    `1`x SET MULTiPLiER ฟ           x=multiplier            [0-F]',
    '    `2`x SET KSL        ๖           x=scaling_level         [0-3]',
    '    `3`x SET TREMOLO    ๖ MOD.      x=off/on                [0-1]',
    '    `4`x SET ViBRATO    ๘           x=off/on                [0-1]',
    '    `5`x SET KSR        ๖           x=off/on                [0-1]',
    '    `6`x SET SUSTAiN    ู           x=off/on                [0-1]',
    '    `7`x SET MULTiPLiER ฟ           x=multiplier            [0-F]',
    '    `8`x SET KSL        ๖           x=scaling_level         [0-3]',
    '    `9`x SET TREMOLO    ๖ CAR.      x=off/on                [0-1]',
    '    `A`x SET ViBRATO    ๘           x=off/on                [0-1]',
    '    `B`x SET KSR        ๖           x=off/on                [0-1]',
    '    `C`x SET SUSTAiN    ู           x=off/on                [0-1]',
    '',
    '`&`?? `0`x PATTERN DELAY (FRAMES)     x=interval              [1-F]',
    '    `1`x PATTERN DELAY (ROWS)       x=interval              [1-F]',
    '    `2`x NOTE DELAY                 x=interval              [1-F]',
    '    `3`x NOTE CUT                   x=interval              [1-F]',
    '    `4`x FiNE-TUNE UP               x=freq_shift            [1-F]',
    '    `5`x FiNE-TUNE DOWN             x=freq_shift            [1-F]',
    '    `6`x GLOBAL VOLUME SLiDE UP     x=speed_of_slide        [1-F]',
    '    `7`x GLOBAL VOLUME SLiDE DOWN   x=speed_of_slide        [1-F]',
    '    `8`x FiNE ~&6x~                   x=speed_of_slide        [1-F]',
    '    `9`x FiNE ~&7x~                   x=speed_of_slide        [1-F]',
    '    `A`x EXTRA FiNE ~&6x~             x=speed_of_slide        [1-F]',
    '    `B`x EXTRA FiNE ~&7x~             x=speed_of_slide        [1-F]',
    '    `C`x EXTRA FiNE VSLiDE UP       x=speed_of_slide        [1-F]',
    '    `D`x EXTRA FiNE VSLiDE DOWN     x=speed_of_slide        [1-F]',
    '    `E`x EXTRA FiNE FSLiDE UP       x=speed_of_slide        [1-F]',
    '    `F`x EXTRA FiNE FSLiDE DOWN     x=speed_of_slide        [1-F]',
    '',
    '`$`xy ฤฤ EXTRA FiNE ARPEGGiO        xy=1st_ซtone|2nd_ซtone  [1-F]',
    '@@`~~`xy ฤฤ EXTRA FiNE ViBRATO         xy=speed|depth          [1-F]  ~C~',
    '`^`xy ฤฤ EXTRA FiNE TREMOLO         xy=speed|depth          [1-F]  ~C~',
    '',
    'Note that effects marked as ~C~ can be continued',
    'in subsequent lines by setting the parameter to value 0.',
    '',
    'For detailed information on effect commands, see the ~adtrack2.doc~ file.',
    '',
    '',
    '                                ฤยฤ       ฤฤ',
    '                           /ดDLiBณR/ดCK3R ณณ SDL',
    '                            ณ       ณ     ฤฤ',
    '                                      '+at2ver+'',
    '',
    '`Get the latest version from:`',
    'http://www.adlibtracker.net',
    '',
    '`Contact information:`',
    'E-MAiL subz3ro@hotmail.com',
    'iCQ#   58622796',
    '',
    '`Credits:`',
    'Florian Klaempfl and others [Free Pascal Compiler 2.6.2]',
    'Japheth [JWasm v2.11]',
    'Joergen Ibsen [aPLib 0.26b]',
    'Simple DirectMedia Layer [SDL 1.2]',
    'Daniel F. Moisset [SDL4Freepascal-1.2.0.0]',
    'Jarek Burczynski and MAME Development Team [ymf262.c version 0.2]',
    'Markus Oberhumer, Laszlo Molnar & John Reiser [UPX 3.91w]',
    '',
    '`subz3ro thanks to:`',
    'Slawomir Bubel (Malfunction/Altair), Daniel Illgen (insane/Altair),',
    'Mikkel Hastrup (encore), Dmitry Smagin, Cecill Etheredge (ijsf),',
    'Florian Jung (Windfisch), Sven Renner (NeuralNET),',
    'Tyler Montbriand (Corona688), and Mr. Maan M. Hamze :-)',
    '',
    '`Greetz fly to the following people:`',
    'Dragan Espenschied (drx/Bodenstandig 2000), Carl Peczynski (OxygenStar),',
    'Hubert Lamontagne (Madbrain), Diode Milliampere, Matej Hudak,',
    'and all others whom I forgot in this list :-)');

const
  key_comment_B =
    '  C   D   E   F   G   A   B   C   D   E   F   G   A   B   C   D   E';
  key_comment_H =
    '  C   D   E   F   G   A   H   C   D   E   F   G   A   H   C   D   E';

const
  shift_f5_1 = '~[Shift] F5~               @F5 with Trace';
  shift_f8_1 = '~[Shift] F8~               @F8 with Trace';
  shift_f9_1 = '~[Shift] F9~               @F9 with Trace';
  alt_f8_1   = '~[Alt] F8~                 @F8 ร without synchronization';

const
  shift_f5_2 = '~[Shift] F5~               @F5 with no Trace';
  shift_f8_2 = '~[Shift] F8~               @F8 with no Trace';
  shift_f9_2 = '~[Shift] F9~               @F9 with no Trace';
  alt_f8_2   = '~[Alt] F8~                 @F8 ร with synchronization';

procedure HELP(topic: String);

var
  temps: String;
  page,temp,fkey: Word;
  xstart,ystart,ypos: Byte;

procedure ListCStr(var dest; x,y: Byte;
                             str: String; atr1,atr2,atr3: Byte);
begin
  If (Copy(str,1,3) = '@@~') then
    begin
      Delete(str,1,3);
      ShowCStr2(dest,x,y,
                ExpStrR(str,74+Length(str)-CStr2Len(str),' '),
                atr1,atr2);
     end
  else If (Copy(str,1,3) = '@@`') then
         begin
           Delete(str,1,3);
           ShowCStr(dest,x,y,
                    ExpStrR(str,74+Length(str)-CStrLen(str),' '),
                    atr1,atr2);
         end
       else ShowC3Str(dest,x,y,
                      ExpStrR(str,74+Length(str)-C3StrLen(str),' '),
                      atr1,atr2,atr3);
end;

begin
  _debug_str_ := 'ADT2TEXT.PAS:Help';
  Move(screen_ptr^,backup.screen,SizeOf(backup.screen));
  backup.cursor := GetCursor;
  backup.oldx   := WhereX;
  backup.oldy   := WhereY;

  HideCursor;
  centered_frame(xstart,ystart,77,MAX_PATTERN_ROWS+8,' HELP ',
                 help_background+help_border,
                 help_background+help_title,
                 double);
  page := 1;
  While (page <= LINES-24) and ((Copy(help_data[page],1,6) <> '@topic') or
        (Copy(help_data[page],8,Length(help_data[page])-7) <> topic)) do
    Inc(page);

  If page < 1 then page := 1;
  If page > LINES-(MAX_PATTERN_ROWS+6) then page := LINES-24;

  Repeat
    If (page > 1) then temps := '' else temps := '-';
    If (page < LINES-(MAX_PATTERN_ROWS+6)) then temps := temps+'' else temps := temps+'-';
    ShowCStr(screen_ptr^,xstart+1+74-Length(temps),ystart+MAX_PATTERN_ROWS+8,
             '[~'+temps+'~]',
             help_background+help_border,
             help_background+help_indicators);
    ypos := ystart+1;
    temp := page;
    While (ypos <= ystart+(MAX_PATTERN_ROWS+6)+1) and (temp <= LINES) do
      begin
        If (Copy(help_data[temp],1,6) <> '@topic') and
           (Copy(help_data[temp],1,6) <> '@input') then
          begin
            If (Copy(help_data[temp],1,3) <> ' บ ') then
              ListCStr(screen_ptr^,xstart+2,ypos,
                       help_data[temp],
                       help_background+help_text,
                       help_background+help_keys,
                       help_background+help_hi_text)
            else
              ListCStr(screen_ptr^,xstart+2,ypos,
                       help_data[temp],
                       help_background+help_text,
                       help_background+help_keys,
                       help_background+help_topic);
            Inc(ypos);
          end
        else If (Copy(help_data[temp],8,
                 Length(help_data[temp])-7) = 'key_comment') then
            begin
              If NOT use_H_for_B then
                ListCStr(screen_ptr^,xstart+2,ypos,
                         key_comment_B,
                         help_background+help_text,
                         help_background+help_keys,
                         help_background+help_topic)
              else
                ListCStr(screen_ptr^,xstart+2,ypos,
                         key_comment_H,
                         help_background+help_text,
                         help_background+help_keys,
                         help_background+help_topic);
              Inc(ypos);
            end
          else If (Copy(help_data[temp],8,
                   Length(help_data[temp])-7) = 'shift_f5') then
            begin
              If NOT trace_by_default then
                ListCStr(screen_ptr^,xstart+2,ypos,
                         shift_f5_1,
                         help_background+help_text,
                         help_background+help_keys,
                         help_background+help_topic)
              else
                ListCStr(screen_ptr^,xstart+2,ypos,
                         shift_f5_2,
                         help_background+help_text,
                         help_background+help_keys,
                         help_background+help_topic);
              Inc(ypos);
            end
          else If (Copy(help_data[temp],8,
                  Length(help_data[temp])-7) = 'shift_f8') then
            begin
              If NOT trace_by_default then
                ListCStr(screen_ptr^,xstart+2,ypos,
                         shift_f8_1,
                         help_background+help_text,
                         help_background+help_keys,
                         help_background+help_topic)
              else
                ListCStr(screen_ptr^,xstart+2,ypos,
                         shift_f8_2,
                         help_background+help_text,
                         help_background+help_keys,
                         help_background+help_topic);
              Inc(ypos);
            end
          else If (Copy(help_data[temp],8,
                   Length(help_data[temp])-7) = 'shift_f9') then
            begin
              If NOT trace_by_default then
                ListCStr(screen_ptr^,xstart+2,ypos,
                         shift_f9_1,
                         help_background+help_text,
                         help_background+help_keys,
                         help_background+help_topic)
              else
                ListCStr(screen_ptr^,xstart+2,ypos,
                         shift_f9_2,
                         help_background+help_text,
                         help_background+help_keys,
                         help_background+help_topic);
              Inc(ypos);
            end
          else If (Copy(help_data[temp],8,
                   Length(help_data[temp])-7) = 'alt_f8') then
            begin
              If NOT nosync_by_default then
                ListCStr(screen_ptr^,xstart+2,ypos,
                         alt_f8_1,
                         help_background+help_text,
                         help_background+help_keys,
                         help_background+help_topic)
              else
                ListCStr(screen_ptr^,xstart+2,ypos,
                         alt_f8_2,
                         help_background+help_text,
                         help_background+help_keys,
                         help_background+help_topic);
              Inc(ypos);
            end;

        Inc(temp);
      end;

    fkey := getkey;
    Case fkey of
      kUP:     begin
                 If page > 1 then Dec(page);
                 If (Copy(help_data[page-1],1,6) = '@topic') and
                    (page > 1) then Dec(page);
               end;

      kDOWN:   begin
                 If (Copy(help_data[page],1,6) = '@topic') and
                    (page < LINES-(MAX_PATTERN_ROWS+6)) then Inc(page);
                 If page < LINES-(MAX_PATTERN_ROWS+6) then Inc(page);
               end;

      kPgUP:   begin
                 If page > 24 then Dec(page,(MAX_PATTERN_ROWS+6)) else page := 1;
                 If (Copy(help_data[page-1],1,6) = '@topic') and
                    (page > 1) then Dec(page);
               end;

      kPgDOWN: begin
                 If (Copy(help_data[page],1,6) = '@topic') and
                    (page < LINES-(MAX_PATTERN_ROWS+6)) then Inc(page);
                 If page+(MAX_PATTERN_ROWS+6) < LINES-(MAX_PATTERN_ROWS+6) then Inc(page,(MAX_PATTERN_ROWS+6)) else
                 page := LINES-(MAX_PATTERN_ROWS+6);
               end;

      kHOME:   page := 1;
      kEND:    page := LINES-(MAX_PATTERN_ROWS+6);
    end;
    emulate_screen;
  until (fkey = kENTER) or (fkey = kESC) or _force_program_quit;

  move_to_screen_data := Addr(backup.screen);
  move_to_screen_area[1] := xstart;
  move_to_screen_area[2] := ystart;
  move_to_screen_area[3] := xstart+77+2;
  move_to_screen_area[4] := ystart+(MAX_PATTERN_ROWS+8)+1;
  move2screen;
end;

procedure C3WriteLn(posX,posY: Byte; str: String; atr1,atr2,atr3: Byte);
begin
  ShowC3Str(screen_ptr^,posX,posY,
            str,
            atr1,atr2,atr3);
end;

procedure ShowStartMessage;

var
  temp: Byte;

begin
  For temp := 0 to 18 do
    adt2_title[temp] := RotStrL('/ดDLiB TR/ดCK3R ][', ' - REViSiON '+at2rev+' - ',temp);

  adt2_title[18] := '-+ REViSiON '+at2rev+' +-';

  For temp := 19 to 36 do
     adt2_title[temp] := RotStrL(' - REViSiON '+at2rev+' - ', '/ดDLiB TR/ดCK3R ][',temp-18);

  WriteLn;
  WriteLn('/ดDLiB TR/ดCK3R ][ SDL (win32)');
  WriteLn('coded by subz3ro/Altair, SDL portation support by Dmitry Smagin');
  WriteLn('version ',at2ver,' built on ',at2date,' ',at2link);
  WriteLn;
end;

end.
