.TH adtrack2 1 "April 21 2017"
.SH NAME
adtrack2 \- userfriendly tracker aimed for the OPL3 FM-chip
.SH SYNOPSIS
.B adtrack2
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B adtrack2
command.
.PP
\fBadtrack2\fP is, dare we say, the most userfriendly tracker aimed for the
OPL3 FM-chip, and is full of advanced features to simplify your task of
making the most of your Adlib-tunes. Supporting 4 operator instruments,
percussion mode, a wide selection of importable song- and instrument types
and - maybe foremost - an advanced macro editor that can really push the
FM-chip to the limit.
.SS Supported file formats
.TP
A2M
AdlibTracker2
.TP
A2P
AdlibTracker2 [pattern]
.TP
A2T
AdlibTracker2 [tiny module]
.TP
AMD
Amusic
.TP
CFF
BoomTracker 4.0
.TP
DFM
Digital-FM
.TP
FMK
FM-Kingtracker
.TP
HSC
HSC AdLib Composer / HSC-Tracker
.TP
MTK
MPU-401 trakker
.TP
RAD
Reality AdLib Tracker
.TP
S3M
Scream Tracker 3.x
.TP
SAT
Surprise! AdLib Tracker {ver.1,5,6}
.TP
SA2
Surprise! AdLib Tracker 2.0 {ver.8,9}
.TP
XMS
XMS-Tracker
.SH SEE ALSO
.BR goattracker (1),
.BR adplay (1).
